name: Common
on:
  push:
    branches: [master, develop]
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/common

defaults:
  run:
    working-directory: packages/common

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --omit=peer
        working-directory: ${{github.workspace}}

      - run: npm run lint
      - run: npm run coverage

      - uses: vebr/jest-lcov-reporter@v0.2.0
        working-directory: ${{github.workspace}}/packages/common
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: /coverage/lcov.info
