name: Common
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/common

defaults:
  run:
    working-directory: packages/common

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - uses: actions/cache/restore@v3
        with:
          path: ${{github.workspace}}
          key: cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --omit=peer
        working-directory: ${{ github.workspace }}

      - uses: actions/cache@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{github.workspace}}
          key: cache-${{ hashFiles('**/package-lock.json') }}

      - run: npm run lint
      - run: npm run coverage

      - uses: Nef10/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ${{github.workspace}}/packages/rlp/coverage/lcov.info
          pr-number: 3130
